#-------------------------------------------------------------------------------
# contra -- a lightweigth transport library for conduit data
#
# Copyright (c) 2018 RWTH Aachen University, Germany,
# Virtual Reality & Immersive Visualization Group.
#-------------------------------------------------------------------------------
#                                  License
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------

stages:
  - conan
  - cmake
  - build
  - test
  
#-------------------------------------------------------------------------------
#  Windows
#-------------------------------------------------------------------------------

conan:windows:msvc++14.1:
  stage: conan
  tags:
    - msvc++14.1
    - opengl
  script:
    - rmdir /s /q build
    - mkdir build
    - cd build
    - conan install --build=missing -s compiler="Visual Studio" -s compiler.version=15 -s build_type=Release -s compiler.runtime=MD ..
  artifacts:
    paths:
      - build
    expire_in: 1 week
    
cmake:windows:msvc++14.1:
  stage: cmake
  tags:
    - msvc++14.1
    - opengl
  dependencies:
    - conan:windows:msvc++14.1
  script:
    - cd build
    - cmake -G "Visual Studio 15 2017 Win64" ..
  artifacts:
    untracked: true
    paths:
    - build
    expire_in: 1 week

build:windows:msvc++14.1:
  stage: build
  tags:
    - msvc++14.1
    - opengl
  dependencies:
    - cmake:windows:msvc++14.1
  script:
    - cd build
    - cmake --build . --config Release
  artifacts:
    paths:
    - build
    expire_in: 1 week
  allow_failure: true

test:windows:msvc++14.1:
  stage: test
  tags:
    - msvc++14.1
    - opengl
  dependencies:
    - build:windows:msvc++14.1
  script:
    - cd build
    - ctest -C Release
