get_filename_component(CURRENT_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)

foreach(COMPONENT ${contra_FIND_COMPONENTS})
    set(COMPONENT_CONFIG_FILE ${CURRENT_DIR}/contra_${COMPONENT}.cmake)

    if(EXISTS ${COMPONENT_CONFIG_FILE})
        include(${COMPONENT_CONFIG_FILE})
        if(NOT ${contra_FIND_QUIETLY})
            message(STATUS "Found contra component: ${COMPONENT}")
        endif(NOT ${contra_FIND_QUIETLY})
    else()
        if(contra_FIND_REQUIRED_${COMPONENT})
            message(SEND_ERROR "Cannot find contra component: ${COMPONENT}")
        else()
            if(NOT ${contra_FIND_QUIETLY})
                message(STATUS "Cannot find contra component: ${COMPONENT}")
            endif(NOT ${contra_FIND_QUIETLY})
        endif()
    endif()
endforeach()
